import type { Metadata } from "next";
import { Rokkitt } from "next/font/google"; 
import "./globals.css";

const rokkit = Rokkitt({
  subsets: ["latin"],
  display: "swap", 
  variable: "--font-rokkit", 
});

export const metadata: Metadata = {
  title: "Seat Map Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={rokkit.variable}>
        {children}
      </body>
    </html>
  );
}
